name: Check & Build

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install

      - name: Run Test
        run: pnpm nx affected --target=test

  Lint:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
         with:
          fetch-depth: 0
       - uses: pnpm/action-setup@v2.2.2
         with:
          version: 7
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
         with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
       - name: Install Dependencies
         run: pnpm install

       - name: Run Lint
         run: pnpm nx affected --target=lint

  Build:
    runs-on: ubuntu-latest
    needs: [Lint, Test]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - uses: nrwl/nx-set-shas@v2
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Install Dependencies
        run: pnpm install

      - name: Pull Vercel Environments
        run: pnpm vercel pull --environment=production --token=${{ secrets.VERCEL_TOKEN }} --yes
      - name: Build
        run: pnpm nx affected --target=build-prod

      - name: Zip Artifacts
        run: zip -r artifacts.zip .vercel/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts.zip
          retention-days: 14

  Deploy:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - uses: nrwl/nx-set-shas@v2
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Install Dependencies
        run: pnpm install

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Unzip Artifacts
        run: unzip artifacts.zip

      - name: Display files
        run: ls -R .vercel/

      - name: Deploy to Vercel
        run: pnpm nx affected --target=deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}


